version: '3'

services:
  proxy:
    image: mjsd/nginx.proxy:latest
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    links:
      - sma.stm.services.genericmessageservice
      - sma.stm.services.authorizationservice
      - sma.stm.services.subscriptionservice
      - sma.stm.ssc.services.private
      - sma.stm.services.notificationservice
      - sma.stm.services.messagesenderservice
    networks:
      - stmnetwork

  sma.stm.services.genericmessageservice:
    image: mjsd/sma.stm.services.genericmessageservice${TAG}
    build:
      context: ./Sma.Stm.Services.GenericMessageService
      dockerfile: Dockerfile
    depends_on:
      - sma.stm.services.authorizationservice
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.services.authorizationservice:
    image: mjsd/sma.stm.services.authorizationservice${TAG}
    build:
      context: ./Sma.Stm.Services.AuthorizationService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.services.subscriptionservice:
    image: mjsd/sma.stm.services.subscriptionservice${TAG}
    build:
      context: ./Sma.Stm.Services.SubscriptionService
      dockerfile: Dockerfile
    depends_on:
      - sma.stm.services.authorizationservice
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.ssc.services.private:
    image: mjsd/sma.stm.ssc.services.private${TAG}
    build:
      context: ./Sma.Stm.Ssc.Services.Private
      dockerfile: Dockerfile
    networks:
      - stmnetwork

  sma.stm.services.notificationservice:
    image: mjsd/sma.stm.services.notificationservice${TAG}
    build:
      context: ./Sma.Stm.Services.NotificationService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.services.messagesenderservice:
    image: mjsd/sma.stm.services.messagesenderservice${TAG}
    build:
      context: ./Sma.Stm.Services.MessageSenderService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - stmnetwork

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - stmnetwork

  postgres:
    image: postgres
    restart: always
    networks:
       - stmnetwork

networks:
  stmnetwork:
     driver: bridge