version: '3'

services:
  sma.stm.services.genericmessageservice:
    image: sma.stm.services.genericmessageservice
    build:
      context: ./Sma.Stm.Services.GenericMessageService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - sma.stm.services.authorizationservice
      - postgres
    networks:
      - stmnetwork

  sma.stm.services.authorizationservice:
    image: sma.stm.services.authorizationservice
    build:
      context: ./Sma.Stm.Services.AuthorizationService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.services.subscriptionservice:
    image: sma.stm.services.subscriptionservice
    build:
      context: ./Sma.Stm.Services.SubscriptionService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - stmnetwork

  sma.stm.ssc.apigateway:
    image: sma.stm.ssc.apigateway
    build:
      context: ./Sma.Stm.Ssc.ApiGateway
      dockerfile: Dockerfile
    networks:
      - stmnetwork

  sma.stm.ssc.services.private:
    image: sma.stm.ssc.services.private
    build:
      context: ./Sma.Stm.Ssc.Services.Private
      dockerfile: Dockerfile
    networks:
      - stmnetwork

  sma.stm.services.notificationservice:
    image: sma.stm.services.notificationservice
    build:
      context: ./Sma.Stm.Services.NotificationService
      dockerfile: Dockerfile
    networks:
      - stmnetwork

  sma.stm.messagesenderservice:
    image: sma.stm.messagesenderservice
    build:
      context: ./Sma.Stm.MessageSenderService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - stmnetwork

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - stmnetwork

  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
       - stmnetwork

volumes:
  pgdata:

networks:
  stmnetwork:
     driver: bridge
