version: '3'

services:
  proxy:
    ports:
      - "8080:443"
      - "8081:444"

  sma.stm.services.genericmessageservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
    ports:
      - "5001:80"

  sma.stm.services.authorizationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
    ports:
      - "5002:80"

  sma.stm.services.subscriptionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
    ports:
      - "5003:80"

  sma.stm.ssc.services.private:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
    ports:
      - "5004:80"

  sma.stm.services.notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
    ports:
      - "5005:80"

  sma.stm.services.messagesenderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBusConnection=rabbitmq
  
  postgres:
    environment:
        POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: